// ignore_for_file: constant_identifier_names
//ENTIDADES DE LA APLICACION CENTRALIZADOS
enum Entities {
  TORGSUCURSAL("TORGSUCURSAL"),
  TPERPERSONA("TPERPERSONA"),
  TSEGROL("TSEGROL"),
  TSEGCANAL("TSEGCANAL"),
  TSEGUSUARIO("TSEGUSUARIO"),
  TSEGROLUSUARIO("TSEGROLUSUARIO"),
  TSEGUSUARIOCANAL("TSEGUSUARIOCANAL"),
  TSEGDISPOSITIVO("TSEGDISPOSITIVO"),
  TSEGSESION("TSEGSESION"),
  TSERCONCEPTO("TSERCONCEPTO"),
  TSERSERVICIOADICIONAL("TSERSERVICIOADICIONAL"),
  TORDORDEN("TORDORDEN"),
  TORDORDENDETALLE("TORDORDENDETALLE"),
  TORDORDENDETALLEADICIONAL("TORDORDENDETALLEADICIONAL"),
  TORDPAGO("TORDPAGO"),
  TFINMOVIMIENTO("TFINMOVIMIENTO");

  final String tableName;
  const Entities(this.tableName);
}
